services:
  - type: web
    name: bts-website
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: gunicorn bts_pc_website.wsgi:application --log-file -
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: mikrokosmos-memo.onrender.com
      - key: CSRF_TRUSTED_ORIGINS
        value: https://mikrokosmos-memo.onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: bts-website-db
          property: connectionString
      - key: CLOUDINARY_URL
        sync: false  
databases:
  - name: bts-website-db
    plan: free
