# Generated by Django 6.0.3 on 2026-04-04 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.CharField(max_length=120, unique=True)),
                ('era', models.CharField(max_length=200)),
                ('version', models.CharField(blank=True, default='', max_length=120)),
                ('member', models.CharField(max_length=60)),
                ('image', models.CharField(blank=True, default='', max_length=255)),
                ('card_type', models.CharField(blank=True, default='', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['era', 'member', 'version', 'card_id'],
            },
        ),
    ]
